language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js: node
script:
  - yarn test && yarn build
after_success:
  - yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
